services:
  challenge180days-prod-php:
    image: "ghcr.io/optimuscrime/180-days-challenge/180-days-challenge-php:latest"
    restart: unless-stopped
    mem_limit: 64m
    ports:
      - "9000"
    env_file:
      - env_php_prod.env
    volumes:
      - ./backend/database:/code/database

  challenge180days-prod-migrations:
    image: "ghcr.io/optimuscrime/180-days-challenge/180-days-challenge-migrations:latest"
    restart: "no"
    mem_limit: 64m
    env_file:
      - env_php_prod.env
    volumes:
      - ./backend/database:/code/database
  
  challenge180days-prod-nginx:
    image: "ghcr.io/optimuscrime/180-days-challenge/180-days-challenge-nginx:latest"
    restart: unless-stopped
    mem_limit: 64m
    ports:
      - "8094:80"
    depends_on:
      - challenge180days-prod-php
    links:
      - challenge180days-prod-php
